export let itemsHouse = [
    {
        img: './assets/img/Видовой_кадр_01_6x6.jpg',
        alt: 'firstTile',
        size: 'Размер: 6x6',
        square: 'Площадь: 71 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '6x6.html',
        typeHouse: 'Мансардия',
        code: '000000003'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x7.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x7',
        square: 'Площадь: 82 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '7x7.html',
        typeHouse: 'Клевер',
        code: '000000033'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x7_с_котельной.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x7 с котельной',
        square: 'Площадь: 82 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '7x7_with_boiler_room.html',
        typeHouse: 'Клевер',
        code: '000000034'
    },
    {
        img: './assets/img/Видовой_кадр_01_6x7.jpg',
        alt: 'firstTile',
        size: 'Размер: 6x7',
        square: 'Площадь: 71 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '6x7.html',
        typeHouse: 'Мансардия',
        code: '000000004'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x11.jpg',
        alt: 'firstTile',
        size: 'Размер: 8x11',
        square: 'Площадь: 124 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '8x11.html',
        typeHouse: 'Шварц',
        code: '000000035'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x11.8.jpg',
        alt: 'firstTile',
        size: 'Размер: 8x11.8',
        square: 'Площадь: 128 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '8x11.8.html',
        typeHouse: 'Шварц',
        code: '000000007'
    },
    {
        img: './assets/img/Видовой_кадр_01_7.5х10.png',
        alt: 'firstTile',
        size: 'Размер: 7.5x10',
        square: 'Площадь: 114 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '7.5x10.html',
        typeHouse: 'Эркерия',
        code: '000000036'
    },
    {
        img: './assets/img/Видовой_кадр_01_8.5x11.jpg',
        alt: 'firstTile',
        size: 'Размер: 8.5x11',
        square: 'Площадь: 130 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '8.5x11.html',
        typeHouse: 'Эркерия',
        code: '000000037'
    },
    {
        img: './assets/img/Видовой_кадр_01_9.5x10.jpg',
        alt: 'firstTile',
        size: 'Размер: 9.5x10',
        square: 'Площадь: 128 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '9.5x10.html',
        typeHouse: 'Эркерия',
        code: '000000038'
    },
    {
        img: './assets/img/Видовой_кадр_01_9.5x12.jpg',
        alt: 'firstTile',
        size: 'Размер: 9.5x12',
        square: 'Площадь: 163 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '9.5x12.html',
        typeHouse: 'Эркерия',
        code: '000000039'
    },
    {
        img: './assets/img/Видовой_кадр_01_10x10.jpg',
        alt: 'firstTile',
        size: 'Размер: 10x10',
        square: 'Площадь: 73 м2',
        coust:  'Стоимость: Скоро будут доступны',
        mortgage: 'Стоимость: Скоро будут доступны',
        type: 'cottage',
        link: '10x10.html',
        typeHouse: 'Галант',
        code: '000000040'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x10.jpg',
        alt: 'firstTile',
        size: 'Размер: 8x10',
        square: 'Площадь: 73 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8x10.html',
        typeHouse: 'Кантри',
        code: '000000013'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x10_(2_спальни).jpg',
        alt: 'firstTile',
        size: 'Размер: 8х10 (2 спальни)',
        square: 'Площадь: 73 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8х10_2_bedrooms.html',
        typeHouse: 'Кантри',
        code: '000000041'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x12.jpg',
        alt: 'firstTile',
        size: 'Размер: 8х12',
        square: 'Площадь: 87 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8x12_country.html',
        typeHouse: 'Кантри',
        code: '000000019'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x13_country.jpg',
        alt: 'firstTile',
        size: 'Размер: 8х13',
        square: 'Площадь: 87 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8x13_country.html',
        typeHouse: 'Кантри',
        code: '000000016'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x12.jpg',
        alt: 'firstTile',
        size: 'Размер: 8х13',
        square: 'Площадь: 87 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8x13_country_2.html',
        typeHouse: 'Кантри',
        code: '000000042'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x8.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x8',
        square: 'Площадь: 94.7 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '7x8.html',
        typeHouse: 'Классик',
        code: '000000031'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x10.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x10',
        square: 'Площадь: 119 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '7x10.html',
        typeHouse: 'Классик',
        code: '000000043'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x8.jpg',
        alt: 'firstTile',
        size: 'Размер: 8x8',
        square: 'Площадь: 109 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '8x8.html',
        typeHouse: 'Классик',
        code: '000000001'
    },
    {
        img: './assets/img/Видовой_кадр_01_8x9.jpg',
        alt: 'firstTile',
        size: 'Размер: 8x9',
        square: 'Площадь: 126 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house',
        link: '8x9.html',
        typeHouse: 'Классик',
        code: '000000005'
    },
    {
        img: './assets/img/Видовой_кадр_01_9.5x14.jpg',
        alt: 'firstTile',
        size: 'Размер: 9.5x14',
        square: 'Площадь: 108 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '9.5x14.html',
        typeHouse: 'Архитект',
        code: '000000045'
    },
    {
        img: './assets/img/Видовой_кадр_01_9.5x13.jpg',
        alt: 'firstTile',
        size: 'Размер: 9.5x13',
        square: 'Площадь: 108 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '9.5x13.html',
        typeHouse: 'Архитект',
        code: '000000044'
    },
    {
        img: './assets/img/Видовой_кадр_01_8.5x12.jpg',
        alt: 'firstTile',
        size: 'Размер: 8.5x12',
        square: 'Площадь: 108 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '8.5x12.html',
        typeHouse: 'Архитект',
        code: '000000046'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x8_cottage.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x8',
        square: 'Площадь: 50 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '7x8_cottage.html',
        typeHouse: 'Микра',
        code: '000000008'
    },
    {
        img: './assets/img/Видовой_кадр_01_5x7.jpg',
        alt: 'firstTile',
        size: 'Размер: 5x7',
        square: 'Площадь: 50 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'cottage',
        link: '5x7.html',
        typeHouse: 'Микра',
        code: '000000047'
    },
    {
        img: './assets/img/Видовой_кадр_01_7x7_attic.jpg',
        alt: 'firstTile',
        size: 'Размер: 7x7',
        square: 'Площадь: 71 м2',
        coust:  'Стоимость: <span></span> руб',
        mortgage: 'В ипотеку: от <span></span> руб',
        type: 'two-storey house', 
        link: '7x7_attic.html',
        typeHouse: 'Мансардия',
        code: '000000014'
    },
    {
        img: './assets/img/Видовой_кадр_01_5x6_bathhouse.jpg',
        alt: 'twentyFourthTile',
        size: 'Размер: 5х6',
        square: 'Площадь: 26 м2',
        coust:  'Стоимость: Скоро будут доступны',
        type: 'bathhouse',
        link: '5x6-bath.html',
        typeHouse: 'Бани',
        code: ''
    } ,
    {
        img: './assets/img/Видовой_кадр_01_8x7_bathhouse.jpg',
        alt: 'twentyFifthTile',
        size: 'Размер: 8х7',
        square: 'Площадь: 33 м2',
        coust:  'Стоимость: Скоро будут доступны',
        type: 'bathhouse',
        link: '8x7-bath.html',
        typeHouse: 'Бани',
        code: ''
    } 
]